### ISSUE TITLE
Support for greater than 512kb uploads? Over Tor?

### ISSUE THREAD

**Issue by hotelzululima** [sametmax/0bin#103]
Hi There,
           I just ran into this limitation in 0bin although cherrypy has tests for greater than 512k uploads..

  Any Ideas?

Warning!
The encrypted file was 1543KB. You have reached the maximum size limit of 500KB.

      thanx in advance
      hzl

**Comment by hotelzululima** [comment]
the justification is for disclosure items such as the recent USG phone lists that got disclosed by a hacker 
so that journalists can gain safe access ie 0bin run under tor..

**Comment by sametmax** [comment]
Your own 0bin setup or ours ?

**Comment by hotelzululima** [comment]
my tor enabled site at http://uhiwoomhaddtjnse.onion/ 
it would be nice to handle any size document or any type.. again this is for post snowden
document handoffs for journalists and their sources on an adhoc basis i believe the use model of 0bin superior to what has been proposed(secure drop) especially when 0bin is accessed via tor...

**Comment by hotelzululima** [comment]
any ideas on how to expand the upload for my own server? ie is there a known path to this?

**Comment by hotelzululima** [comment]
MAX_SIZE is working correctly had installed eggs confused.. closing thanx sorry to have wasted time on this
