### ISSUE TITLE
Replace the cherrypy/wsgiserver with latest cherrypy/cheroot

### ISSUE THREAD

**Issue by CryptoSiD** [sametmax/0bin#115]
wsgiserver has been replaced with cheroot and we have to downgrade it to be able to run 0bin server.

**Comment by sametmax** [comment]
Hello, 

We haven't updated 0bin for a while. There is a lot of work to be done on it. Unfortunately we currently lack the time to do so, as we are creating a new company right now.

So it's on hold. Sorry about that.
