### ISSUE TITLE
Bad website cert

### ISSUE THREAD

**Issue by dessalines** [sametmax/0bin#119]
![img](https://i.imgur.com/ItZQagL.png)

**Comment by sametmax** [comment]
Can't reproduce. Can you show me the certificate ?

Le 14/10/2018 à 21:45, Dessalines a écrit :

**Comment by Glandos** [comment]
The certificate subject is `0bin.net`. The `subjectAlternativeName` is also `0bin.net`.
So yes, when going to `www.0bin.net`, the domain doesn't match.

```sh
> echo "" | openssl s_client -connect www.0bin.net:443 2> /dev/null | openssl x509 -text | grep -A3 -P 'Subject(:| Alternative)'
        Subject: CN = 0bin.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
--
            X509v3 Subject Alternative Name: 
                DNS:0bin.net
            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1
```

**Comment by sametmax** [comment]
The thing is we have a redirection from www.0bin.net to 0bin.net and I tested it on 3 machines, one Linux, one Windows, and one android. All of them redirect.

Are you getting only this error by accessing the website programmatively or do you get it using a web browser ?

Le 15/10/2018 à 09:55, Glandos a écrit :

**Comment by Glandos** [comment]
Yes, but maybe the user entered the HTTPS manually (I doubt it), or (s)he uses something like HTTPS-Everywhere.
You could either:
- Add a `subjectAlternativeName` to your CSR for Let's Encrypt.
- Use wildcard certificate.
- Do nothing. After all, it should only affect a very small portion of users. Check your logs for that.

**Comment by sametmax** [comment]
Ok, thanks. subjectAlternativeName seems the best way to go.. |

|
Le 15/10/2018 à 13:48, Glandos a écrit :

**Comment by dessalines** [comment]
I still get this error when coming to it from: 

https://duckduckgo.com/?q=0bin+&t=ffab&ia=web

**Comment by sametmax** [comment]
I get the same indeed.

Le 15/10/2018 à 19:43, Dessalines a écrit :

**Comment by dessalines** [comment]
This appears to be fixed.
