### ISSUE TITLE
Remove mention of truecrypt in FAQ

### ISSUE THREAD

**Issue by gagou9** [sametmax/0bin#74]
Hello,
not sure it's the right place for that but anyway,

In the FAQ (http://0bin.net/faq/), it's advised to use truecrypt for volume/files encryption. 
This should be changed to whatever still works (https://prism-break.org/en/all/#disk-encryption) !

Cheers, and thanks a lot for having put new work on zerobin !

**Comment by Shir0kamii** [comment]
Can be closed
