### ISSUE TITLE
comparison to Up1

### ISSUE THREAD

**Issue by elijh** [sametmax/0bin#78]
Great project. Are you aware of the similar Up1? https://github.com/Upload/Up1

It also uses SJCL, but with go backend. It would be useful to have a comparison of the approaches and capabilities of these similar projects.

**Comment by Natim** [comment]
Up1 looks great and the scope looks pretty similar to what 0bin propose. 0bin started more as an experiment of porting zerobin in python.

**Comment by v6** [comment]
// , If I made a list of this sort of "host does not know" technology, do
you think https://freedom.press/organization/leap-encryption-access-project
would use it?

**Comment by elijh** [comment]
@v6, as it happens, I plan to add either Up1 or 0bin or imgbi to the LEAP platform, making it really easy to deploy your own (with hidden service to boot).

**Comment by sametmax** [comment]
While I'm glad other open source exists, I don't really see the point of opening a ticket to mention it. This is not a discussion board, but a technical tool. Post this on reddit, and if you want to notify us, send us an email, but don't use the tracker for this please.

**Comment by v6** [comment]
// ,

Quite correct, sametmax. I'll heed what you say.

**Comment by elijh** [comment]
@sametmax it is customary to include in a project's README a mention of other projects with similar or identical functionality.

**Comment by k3d3** [comment]
@elijh not sure if you noticed, but I responded to you on reddit.

**Comment by sametmax** [comment]
@sametmax: that's a good point, we can open a ticket just for that, and mention in 1up next to PHP zerobin.
