### ISSUE TITLE
git version of 0bin not starting

### ISSUE THREAD

**Issue by lenisko** [sametmax/0bin#93]
Just reporting, git version of 0bin is not working out of the box, I mean;
```
$ python zerobin.py
Traceback (most recent call last):
  File "zerobin.py", line 4, in <module>
    from zerobin.routes import main
ImportError: cannot import name main
```

**Comment by Shir0kamii** [comment]
The PR #91 fix this. But thank you for reporting anyway ! ;)

**Comment by lenisko** [comment]
Oh, you got me. It's not pulled and I didn't noticed it : )
