### ISSUE TITLE
Lockfile issue

### ISSUE THREAD

**Issue by lenisko** [sametmax/0bin#94]
There are some problems with lockfile, easy to solve thou.

**libs/cherrypy/lib/sessions.py**
is using self.lock = lockfile.LockFile(path)

same goes for **zerobin/paste.py**
lock = lockfile.LockFile(counter_file)

In my case, running dir on lockfile returns this:

```
['AlreadyLocked', 'Error', 'FileLock', 'LinkFileLock', 'LockBase', 'LockError', 'LockFailed', 'LockTimeout', 'MkdirFileLock', 'NotLocked', 'NotMyLock', 'SQLiteFileLock', 'UnlockError', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'division', 'errno', 'os', 'socket', 'sys', 'thread', 'threading', 'time', 'urllib']
```

**Comment by kelek-** [comment]
push

**Comment by kelek-** [comment]
+1

**Comment by witsch** [comment]
Btw, the latest [lockfile](https://pypi.python.org/pypi/lockfile/0.12.2) release states:

>  **This package is deprecated**. It is highly preferred that instead of using this code base that instead [fasteners](https://pypi.python.org/pypi/fasteners) or [oslo.concurrency](http://docs.openstack.org/developer/oslo.concurrency/) is used instead.

**Comment by ashok-arora** [comment]
Why did you reopen it ?

**Comment by lenisko** [comment]
@ashok-arora mistake I guess :-)
