### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by CorbanR** [sametmax/0bin#96]
Any thoughts on adding LDAP Integration.

**Comment by sametmax** [comment]
LDAP is for authentication, 0bin is anonymous. How do you see the 2 work
together ?

**Comment by Natim** [comment]
If what you want is to only let people from your LDAP access your instance of 0bin, I would propose you to setup a SAML plugin in the Apache or Nginx that will then ProxyPass to the zerobin python application.

**Comment by CorbanR** [comment]
The idea was to use 0bin as a secure / easy way to share secrets within a particular company or group. 0bin would be behind an Nginx proxy with full SSL. It would be nice to ensure (even though it's anonymous) that the people viewing the links are members of a particular AD group. 

I have looked into using https://github.com/kvspb/nginx-auth-ldap, but would prefer not to recompile Nginx. Mostly just a preference, and was wondering if anyone else was interested in 0bin supporting ldap.

**Comment by sametmax** [comment]
0bin is NOT meant to share secrets. Read the FAQ.

**Comment by CorbanR** [comment]
I ready the FAQ, but thought with ldap, ssl, it could be used to securely share secretes, especially with the burn after reading feature. But I understand. Thank you for your quick replies.
